export const article: string;
export const article__tags: string;
export const articleTags: string;
export const article__datetime: string;
export const articleDatetime: string;
export const article__intro: string;
export const articleIntro: string;
export const article__read_more: string;
export const articleReadMore: string;
